<a href="https://colab.research.google.com/github/saketh105/Data690/blob/main/part04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 1}, sys])

In [ ]:
d.dtype

dtype('O')

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
type(C[0])

list

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
a + b

array([110, 111, 112, 113])

In [ ]:
a * b

array([1000, 1010, 1020, 1030])

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[38, 37, 92],
       [41, 28,  0],
       [32, 65, 89]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([38, 92, 28, 32, 89])

In [ ]:
A > 30

array([[ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True]])

In [ ]:
A[A > 30]

array([38, 37, 92, 41, 32, 65, 89])

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize


1

In [ ]:
np.dtype(float).itemsize

8

In [ ]:
# A one-element list
sys.getsizeof([1])

80

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 1.48 ms, sys: 1.09 ms, total: 2.57 ms
Wall time: 2.1 ms


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 34.8 ms, sys: 1.88 ms, total: 36.7 ms
Wall time: 37.3 ms


333328333350000

In [ ]:
np.random.random(size=2)

array([0.26266162, 0.78988146])

In [ ]:
np.random.normal(size=2)

array([ 1.36589179, -0.70978663])

In [ ]:
np.random.rand(2, 4)

array([[0.47900089, 0.34955059, 0.53814144, 0.0309093 ],
       [0.59174892, 0.50284552, 0.85838567, 0.09064677]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.zeros(5)
np.zeros((3, 3))
np.zeros((3, 3), dtype=np.int)
np.ones(5)
np.ones((3, 3))
np.empty(5)
np.empty((2, 2))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [ ]:
np.identity(3)
np.eye(3, 3)
np.eye(8, 4)
np.eye(8, 4, k=1)
np.eye(8, 4, k=-3)
"Hello World"[6]

'W'